# Site settings 配置站点
title: 'skyming的小屋'
description: '其实我是一个程序员'
keyword: 'skyming, 博客, skyming的博客, blog, 程序员, Java, javascript, 后端, 微信小程序, 算法， 数据结构,SQL ,mybatis，科比，美食，做饭'
url: 'http://liaokeyu.com' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'
  about: '/about.html'

# Footer
footer:
  since: 2017

# Author 配置博主信息
author: 'skyming'
nickname: 'MT'
bio: '其实我是一个程序员'
avatar: '/assets/img/author_avatar.png'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/skyming1024'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md','FORK-README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]

# 百度统计
baidu_analysis: 7df116dd7ab0cb0f16455501fb2b8edc